# For extensive Taplo config
# See: https://taplo.tamasfe.dev/configuration/file.html

include = ["pyproject.toml", "src/**/*.toml"]

[formatting]
align_comments = true
array_trailing_comma = true
compact_arrays = false
reorder_keys = true
reorder_arrays = true
reorder_inline_tables = true

[[rule]]
include = ["pyproject.toml"]
keys = ["build-system", "project"]

[rule.formatting]
reorder_keys = false
